[package]
name ="src_modules"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
oracle = "0.6.3"
tokio = { version = "1", features = ["full"] }